version: "3.9"

services:

  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: example
